<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WKWZTP9hkzSNER5" failures="1" tests="8" name="Test3" time="20.437" errors="0" timestamp="2022-11-23T20:33:18 IST">
  <testcase classname="day3.MyFirstTestNGTest" name="deleteAccount" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at day3.MyFirstTestNGTest.deleteAccount(MyFirstTestNGTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- deleteAccount -->
  <testcase classname="day3.MyFirstTestNGTest" name="createAccount" time="0.001"/>
  <testcase classname="day3.MyFirstTestNGTest" name="login" time="0.001"/>
  <testcase classname="day3.Task7" name="dayThreeProgram" time="3.956"/>
  <testcase classname="day3.SmokeTest" name="RightPassword" time="4.219"/>
  <testcase classname="day3.SmokeTest" name="WrongPassword" time="1.224"/>
  <testcase classname="day3.SmokeTest" name="verifyBlank" time="0.262"/>
  <testcase classname="day3.MyFirstTestNGTest" name="logOut" time="0.0">
    <skipped/>
  </testcase> <!-- logOut -->
</testsuite> <!-- Test3 -->
